### ISSUE TITLE
Blank columns in output

### ISSUE THREAD

**Issue by nathankota** [agrc/DEQ-TankRisk#19]
After DEQ testing of [beta.2](https://github.com/agrc/DEQ-TankRisk/releases/tag/2.0.0-beta.2):

> It ran, but the last two columns were blank.

**Comment by nathankota** [comment]
When the tool is run on all layers the last two columns of the output csv are not populated:
`udwspzVal`
`udwspzSev`

The ArcMap output csv from 12/4:
![image](https://user-images.githubusercontent.com/15659642/70755329-c91ee880-1cf6-11ea-80ce-269bc1cf8d64.png)

beta.2 run on 12/12:
![image](https://user-images.githubusercontent.com/15659642/70755384-ece22e80-1cf6-11ea-93de-02a8f260eeab.png)

**Comment by steveoh** [comment]
ok i think i know why the 0's aren't showing but I will have to look into the other cases.
