### ISSUE TITLE
Utilize "Open" Data

### ISSUE THREAD

**Issue by nathankota** [agrc/DEQ-TankRisk#21]
The tool utilizes SGID10 data layers. As SGID10 is deprecated, the tool will need to read data from OpenSGID or Open Data. 

User attempted to run the tool with opensgid and open data layers, the order of operations for that test was:

1. Received Greg's email about future SGID10 deprecation
2. Connected to Open SGID in Pro project
3. Added layers necessary for the Tank Risk Assessment tool
4. Utah Soils layer is not in the Open SGID, so left that layer out
5. Ran the tool
6. Tool failed with the following errors:
![image](https://user-images.githubusercontent.com/15659642/89192633-feb46280-d561-11ea-94b8-a79f121a2809.png)
7. Contacted AGRC about a) possibility of getting Utah Soils in OpenSGID and b) updating the tool to work with one or the other of the "open" offerings (database or open data services).
8. Added Open Data services to Pro project for each layer needed to run the tool.
9. Renamed each layer to the [expected list of layers](https://github.com/agrc/DEQ-TankRisk/blob/master/src/tank_risk.py#L133-L144).
10. Ran the tool and received the following error message:
![image](https://user-images.githubusercontent.com/15659642/89313391-ababdf80-d635-11ea-9b38-c2bb13fdac9c.png)

**Comment by nathankota** [comment]
The fact that [Utah Soils](https://opendata.gis.utah.gov/datasets/utah-soils) is in Open Data but not OpenSGID may influence a decision.

**Comment by nathankota** [comment]
/remind me about this on October 1, 2020

**Comment by steveoh** [comment]
What's going on here?

**Comment by nathankota** [comment]
Eventual switch to Open SGID and/or Open Data sources for the DEQ Tank Risk Tool, some time before SGID10 is deprecated.

**Comment by nathankota** [comment]
Data layers utilized in the Tank Risk Assessor tool:

![image](https://user-images.githubusercontent.com/15659642/95918844-c2735e80-0d69-11eb-96b4-e32cf1d39336.png)

Open Data layers:

- [FacilityUST](https://opendata.gis.utah.gov/datasets/utah-deq-underground-storage-tanks)
- [StreamsNHD](https://opendata.gis.utah.gov/datasets/utah-streams-nhd)
- [LakesNHD](https://opendata.gis.utah.gov/datasets/utah-lakes-nhd)
- [CensusTract2010](https://opendata.gis.utah.gov/datasets/utah-census-tracts-2010)
- [ShallowGroundWater](https://opendata.gis.utah.gov/datasets/utah-shallow-ground-water)
- [Soils](https://opendata.gis.utah.gov/datasets/utah-soils?geometry=-117.836%2C36.517%2C-104.895%2C42.446)
- [DWQAssessmentUnits](https://opendata.gis.utah.gov/datasets/utah-dwq-assessment-units)
- [Aquifer_RechargeDischargeAreas](https://opendata.gis.utah.gov/datasets/utah-aquifer-recharge-discharge-areas)

**Comment by nathankota** [comment]
@steveoh Looks like all of the SGID10 layers above are in Open Data / AGOL except for the NHDHighRes? 

![image](https://user-images.githubusercontent.com/15659642/95923025-ce631e80-0d71-11eb-8175-601cd5f04854.png)

**Comment by steveoh** [comment]
You'll have to ask @ZachBeck and the data folks about those I suppose. It appears it should have based on https://docs.google.com/spreadsheets/d/1FNCvSQxgQbFG--k3ZapscsTapbrxtSGlKqMcMLCsTYs/edit#gid=1144639718 but maybe there is a problem downstream?

**Comment by nathankota** [comment]
I'm hoping so, but the part that threw me off was

> The derivation and modification process has been performed by AGRC to provide a general purpose feature class of water bodies for cartographic purposes.

I'll look into it more today and delete these comments if I find they are the "HighRes" NHD layers.

**Comment by ZachBeck** [comment]
We added fields IsMajor and InUtah to the nhd lakes and streams that is probably for the cartographic purposes that is being referred to. Looks like those fields are in OpenSGID.

**Comment by nathankota** [comment]
Rick replaced all of the SGID10 layers with Open Data services and the tool ran successfully. He had to rename all of the layers to match the SGID10 layer names. I will create a new issue for the tool to recognize the Open Data service names.
