### ISSUE TITLE
FacilityID

### ISSUE THREAD

**Issue by rsaathoff** [agrc/DEQ-TankRisk#31]
Something is different with the facilityid from the old tool to the new tool.  One issue is that it needs to be named FACILITYID in all caps; however I tried just renaming the column heading and it still didn't like the file on that field.

![image](https://user-images.githubusercontent.com/76059382/187971728-c0a93f8b-1d61-4d68-a4d4-4d0b9cdfba6d.png)

**Comment by steveoh** [comment]
What are your inputs to the tool with their data sources?

**Comment by rsaathoff** [comment]
opensgid.environment.petroleum_storage_tank_facilities

**Comment by steveoh** [comment]
postgres has all lowercase field names. Why do you think it needs to be uppercase?

**Comment by rsaathoff** [comment]
The old tool or perhaps the source had uppercase and the tool I use to import is expecting uppercase for some reason.  The programmer that designed the import tool has retired and nobody can work on it right now.

**Comment by steveoh** [comment]
Yeah, the SGID you used to connect to was upper cased. That isn't the case any longer. I suppose you could bring it local and rename it and use that as the source.

**Comment by rsaathoff** [comment]
if I change the view that supplies the opensgid so it is uppercase will that change it to uppercase in the opensgid layer or no?

**Comment by steveoh** [comment]
You have no edit rights in the open sgid. I don't think any view changes will make a difference. That may only be presentational or an alias for your project. If that works for you then great. But this isn't something we can fix. If you agree we can close this issue.

**Comment by rsaathoff** [comment]
I don't agree. How do we change the open sgid?

**Comment by steveoh** [comment]
You don't. It's a database convention. Every postgresql database is lowercase fields.

**Comment by rsaathoff** [comment]
hmm

**Comment by steveoh** [comment]
> The programmer that designed the import tool has retired and nobody can work on it right now.

Gaining access and fixing the import tool seems like the correct solution

**Comment by rsaathoff** [comment]
k, I will see what I can do, thanks
