### ISSUE TITLE
wetlands data layer replacement

### ISSUE THREAD

**Issue by nathankota** [agrc/DEQ-TankRisk#34]
- possibly the [usfws map service](https://fwspublicservices.wim.usgs.gov/wetlandsmapservice/rest/services/Wetlands/MapServer/0) 
- or allow DEQ staff to use the latest version of the [usfws downloaded layer](https://www.fws.gov/node/264847)?

**Comment by steveoh** [comment]
The map service uses the spatial reference of 3857 (web mercator) vs the rest of the layers in 26912 (UTM). I believe as long as the pro mxd has the correct spatial reference of 26912, then the usfws map service will be projected and not have issues with area calculation. i'm setting up my test environment in citrix to try it out and documenting how to do that since it wasn't don't prior.

**Comment by steveoh** [comment]
I'm having issues with the availability of the arcgis service. 

> The server took too long to answer. The client has timed out. 

I downloaded the gdb, reprojected to utm, and am testing with that.
I deleted a bunch of rows (the source has >200k) to make it process faster. It still took about 7 minutes. I'd like to compare our deprecated wetlands to this federal data to see how much it has changed.

But it did run and gave similar results to the csv you shared with me.

**Comment by nathankota** [comment]
although the deprecated wetlands are still in internal until the hard delete occurs, I dropped both the fed download and the former sgid layer in [here](https://drive.google.com/drive/u/0/folders/1q3fJ3CGxeoqt9FHt_kCpncVokGlkLiLb)

**Comment by steveoh** [comment]
Do we know how much processing went into the data we served vs what the feds are providing now? @rkelson were you doing any of that?

**Comment by rkelson** [comment]
I do not. @ZachBeck has been working with them all these years to update what is in internal. I think DNR did the processing then sent it to him. Not sure if the DEQ app needs all the attribute DNR would provide or if it can simply use the few attribute FWS provides.

**Comment by steveoh** [comment]
Fortunately attributes aren't important to this tool. The Tank Risk app adds numeric points based on a near table so it only needs geometry. I'm wondering if there are more geometry types in the fed data that need to be filtered out but I have yet to dive into that.

**Comment by steveoh** [comment]
The data appears to be equivalent.

**Comment by nathankota** [comment]
validated by client April 6, 2023
