### ISSUE TITLE
GroundWaterZones - Unknown risk layer

### ISSUE THREAD

**Issue by rsaathoff** [agrc/DEQ-TankRisk#37]
When I ran the tool this month I am getting an error on the GroundWaterZones.  I downloaded a new copy of tool 2.1.6.  I also deleted the GroundWaterZones layer and added it back using: https://services2.arcgis.com/NnxP4LZ3zX8wWmP9/arcgis/rest/services/Utah_DDW_Groundwater_Source_Protection_Zones/FeatureServer/4

Hopefully this image comes through:
Start Time: Wednesday, September 6, 2023 8:37:08 AM
Version 2.1.6
Unknown risk layer GroundWaterZones

![image](https://github.com/agrc/DEQ-TankRisk/assets/76059382/0b445349-d247-424f-8ad0-fdffdf213fc2)

**Comment by steveoh** [comment]
It seems the feature service changed. The tool was expecting the layer to be id 0 and it's now 4.

https://github.com/agrc/DEQ-TankRisk/blob/f08916d01847c1f3f6482f58481560fd915fe89b/src/tank_risk_tool.pyt#L689

<img width="235" alt="image" src="https://github.com/agrc/DEQ-TankRisk/assets/325813/240a33a6-1b5a-446e-86b7-47a188e8430e">

The tool can be updated to match or the service can be republished with the id updated back to 0. `dbeck_utahdeq` owns the item if you want to ask them.

**Comment by nathankota** [comment]
I will chat with Deidre and make sure we have the correct service.

**Comment by nathankota** [comment]
The correct service is id 4, as also indicated by the [new interactive map's use of it](https://docs.google.com/spreadsheets/d/1aVJ68hOyp4H6sKEEuL-xtB2qE_y6W0gDg35TgUSxtFg). I'm going to close this issue and open a new one to have the tool updated to use the proper service.

**Comment by steveoh** [comment]
@rsaathoff if you make this change in the tool you've downloaded it will start processing that layer again.

https://github.com/agrc/DEQ-TankRisk/commit/4bf0e285fb11f1758326cfd3754db94bb3d28a44
